import "server-only";

// =============================================================================
// NaKmetiji.si — Kronika sender
// Stores a draft as kronika_entries row, then batch-sends to every confirmed,
// non-unsubscribed subscriber via Resend. Fire-and-forget tolerant of missing
// RESEND_API_KEY so CI runs don't explode. Returns counts for audit display.
// =============================================================================

import { Resend } from "resend";
import type { SupabaseClient } from "@supabase/supabase-js";
import * as Sentry from "@sentry/nextjs";
import { generateKronikaDraft, type KronikaDraft } from "./generator";

const FROM = "Jože @ NaKmetiji <jozetovakronika@nakmetiji.si>";
const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? "https://nakmetiji.si";
const BATCH_SIZE = 40; // Resend API allows ~100/sec; we pace to 40 per batch

function getResend(): Resend | null {
  const key = process.env.RESEND_API_KEY;
  if (!key) {
    Sentry.captureMessage("Kronika: RESEND_API_KEY missing — skipping email send", "warning");
    return null;
  }
  return new Resend(key);
}

/** Minimal markdown → inlined HTML. Avoids shipping an MD renderer to the
 *  edge — Kronika body_md is trusted (generated by us) so the subset is OK. */
function markdownToHtml(md: string): string {
  return md
    .replace(/^# (.*)$/gm, '<h1 style="color:#2D5A27;font-family:Georgia,serif">$1</h1>')
    .replace(/^## (.*)$/gm, '<h2 style="color:#2D5A27;font-family:Georgia,serif;margin-top:28px">$1</h2>')
    .replace(/^### \[(.+?)\]\((.+?)\)$/gm,
      '<h3 style="margin:18px 0 6px 0"><a href="$2" style="color:#2D5A27;text-decoration:none;border-bottom:1px dotted #2D5A27">$1</a></h3>')
    .replace(/^### (.*)$/gm, '<h3>$1</h3>')
    .replace(/^> \*(.+)\*$/gm,
      '<blockquote style="border-left:3px solid #d4a86a;background:#fdf8ee;padding:12px 16px;margin:16px 0;font-style:italic;font-family:Georgia,serif;color:#2D5A27">$1</blockquote>')
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/\[(.+?)\]\((.+?)\)/g,
      '<a href="$2" style="color:#2D5A27;text-decoration:underline">$1</a>')
    .replace(/^---$/gm, '<hr style="border:none;border-top:1px solid #e0dcd2;margin:24px 0"/>')
    .replace(/\n\n/g, '</p><p style="margin:14px 0;line-height:1.6;color:#3a3a32">')
    .replace(/^/, '<p style="margin:14px 0;line-height:1.6;color:#3a3a32">')
    .concat("</p>");
}

function wrapEmailHtml(subject: string, innerHtml: string, unsubscribeUrl: string): string {
  return `<!doctype html>
<html lang="sl"><head><meta charset="utf-8"><title>${subject}</title></head>
<body style="margin:0;padding:0;background:#f4f1ea;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif">
  <div style="max-width:620px;margin:0 auto;padding:24px 20px">
    <div style="background:white;border-radius:16px;padding:28px 28px 24px 28px;box-shadow:0 2px 12px rgba(0,0,0,0.04)">
      ${innerHtml}
      <hr style="border:none;border-top:1px solid #e0dcd2;margin:28px 0 16px 0"/>
      <p style="font-size:12px;color:#8a8578;text-align:center;line-height:1.5">
        Prejeli ste to sporočilo, ker ste naročeni na <strong>Jožetovo Kroniko</strong>.<br/>
        <a href="${unsubscribeUrl}" style="color:#8a8578">Odjavi se</a> &middot;
        <a href="${BASE_URL}" style="color:#8a8578">nakmetiji.si</a>
      </p>
    </div>
  </div>
</body></html>`;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface KronikaSendResult {
  issue_number: number;
  slug: string;
  draft: KronikaDraft;
  subscribers_total: number;
  subscribers_sent: number;
  subscribers_failed: number;
  resend_enabled: boolean;
}

export async function generateAndSendKronika(
  sb: SupabaseClient,
  opts: { dryRun?: boolean; createdBy?: string | null } = {},
): Promise<KronikaSendResult> {
  // 1. Draft
  const draft = await generateKronikaDraft(sb);

  // 2. Pick next issue number + persist entry (service role — RLS bypass OK)
  const { data: issueNumData } = await sb.rpc("kronika_next_issue_number");
  const issueNumber = (issueNumData as number | null) ?? 1;

  if (!opts.dryRun) {
    const { error: insertErr } = await sb.from("kronika_entries").insert({
      issue_number: issueNumber,
      slug: draft.slug,
      week_start: draft.week_start,
      week_end: draft.week_end,
      title: draft.title,
      intro: draft.intro,
      new_farm_ids: draft.new_farm_ids,
      proverb: draft.proverb,
      proverb_register: draft.proverb_register,
      body_md: draft.body_md,
      created_by: opts.createdBy ?? null,
    });
    if (insertErr) {
      Sentry.captureMessage(`Kronika insert failed: ${insertErr.message}`, "error");
      throw new Error(insertErr.message);
    }
  }

  // 3. Fetch confirmed subscribers
  const { data: subs } = await sb
    .from("kronika_subscribers")
    .select("email, confirm_token")
    .not("confirmed_at", "is", null)
    .is("unsubscribed_at", null);

  const subList = (subs as Array<{ email: string; confirm_token: string | null }> | null) ?? [];
  const resend = getResend();
  const resendEnabled = !!resend;

  let sent = 0;
  let failed = 0;

  if (resend && !opts.dryRun && subList.length > 0) {
    const html = markdownToHtml(draft.body_md);
    // Batch so we don't hit Resend rate limits on large lists
    for (let i = 0; i < subList.length; i += BATCH_SIZE) {
      const batch = subList.slice(i, i + BATCH_SIZE);
      await Promise.all(
        batch.map(async (s) => {
          const unsubUrl = `${BASE_URL}/kronika/odjava?t=${encodeURIComponent(s.confirm_token ?? "")}&e=${encodeURIComponent(s.email)}`;
          const wrapped = wrapEmailHtml(draft.title, html, unsubUrl);
          try {
            await resend.emails.send({
              from: FROM,
              to: s.email,
              subject: draft.title,
              html: wrapped,
              headers: {
                "List-Unsubscribe": `<${unsubUrl}>`,
                "List-Unsubscribe-Post": "List-Unsubscribe=One-Click",
              },
            });
            sent += 1;
          } catch (err) {
            failed += 1;
            Sentry.captureException(err, {
              tags: { route: "kronika.send" },
              extra: { email: s.email },
            });
          }
        }),
      );
    }

    // Update sent_count on the issue row
    await sb
      .from("kronika_entries")
      .update({ sent_count: sent })
      .eq("slug", draft.slug);
  }

  return {
    issue_number: issueNumber,
    slug: draft.slug,
    draft,
    subscribers_total: subList.length,
    subscribers_sent: sent,
    subscribers_failed: failed,
    resend_enabled: resendEnabled,
  };
}
