-- =============================================================================
-- NaKmetiji.si — Znamenitosti (POI) + Green Passport tables
-- Migration: 20260412_znamenitosti_green_stamps
-- =============================================================================

-- ── 1. Znamenitosti — Points of Interest ──────────────────────────────────────
-- Used by the Oracle AI concierge for geo-enrichment:
-- "3 km from the farm you'll find Slap Savica..."

CREATE TABLE IF NOT EXISTS public.znamenitosti (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  ime         TEXT        NOT NULL,
  opis        TEXT,
  zanimivost  TEXT,                     -- interesting fact / "did you know"
  kategorija  TEXT        NOT NULL CHECK (kategorija IN ('slap','gora','pot','muzej','jezero','jama')),
  lat         DOUBLE PRECISION NOT NULL,
  lng         DOUBLE PRECISION NOT NULL,
  slika_url   TEXT,
  regija      TEXT        NOT NULL
);

-- Index for bounding-box pre-filter (faster than full Haversine scan)
CREATE INDEX IF NOT EXISTS idx_znamenitosti_regija ON znamenitosti (regija);
CREATE INDEX IF NOT EXISTS idx_znamenitosti_lat_lng ON znamenitosti (lat, lng);

-- Anyone can read landmarks (they're public POIs)
ALTER TABLE public.znamenitosti ENABLE ROW LEVEL SECURITY;
CREATE POLICY "znamenitosti_javno" ON public.znamenitosti FOR SELECT USING (true);
CREATE POLICY "znamenitosti_admin" ON public.znamenitosti FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profili WHERE id = auth.uid() AND vloga = 'super_admin')
);

-- ── 2. Seed: ~190 verified Slovenian landmarks ────────────────────────────────
INSERT INTO public.znamenitosti (ime, opis, zanimivost, kategorija, lat, lng, slika_url, regija) VALUES
  ('Slap Savica', '78 m visok slap v obliki ščita pri Bohinjskem jezeru — ena od slovensih ikon.', 'France Prešeren je Savici posvetil svojo najpomembnejšo pesnitev — romantično pesnitev Krst pri Savici (1836).', 'slap', 46.2881, 13.8078, NULL, 'gorenjska'),
  ('Triglav (2864 m)', 'Najvišji vrh Slovenije in simbol naroda — trikotna piramida sredi Julijskih Alp.', 'Vsak Slovenec bi moral po tradiciji vsaj enkrat v življenju splezati na Triglav. Vrh je bil prvič dosežen leta 1778.', 'gora', 46.3789, 13.8369, NULL, 'gorenjska'),
  ('Blejski grad', 'Srednjeveški grad na pečini 130 m nad Blejskim jezerom — najstarejša slovenska trdnjava.', 'Grad stoji na skali, ki je bila poseljena že v kameni dobi. Najstarejši pisni vir omenja grad leta 1011.', 'muzej', 46.3694, 14.09, NULL, 'gorenjska'),
  ('Blejsko jezero', 'Ledeniško jezero z romantičnim otokom in cerkvijo — najprepoznavnejša slovenska pokrajinska slika.', 'Jezero je nastalo pred 14.000 leti ob umiku ledenika. Globoko je 30,6 m in se poleti segreje do 26 °C.', 'jezero', 46.3633, 14.0983, NULL, 'gorenjska'),
  ('Blejski otok', 'Edini naravni otok v Sloveniji z baročno cerkvijo Marijinega vnebovzetja, dosegljiv z lesenim pletnom.', 'Na otoku je cerkveni zvon — po tradiciji ga sme zazvoniti vsak obiskovalec in zaželeti si. Pletnarji veslajo brez vesla — s posebnim potiskanjem.', 'muzej', 46.3633, 14.0936, NULL, 'gorenjska'),
  ('Blejski Vintgar', '4 km dolga soteska reke Radovne s slapovi, tolmuni in lesenimi mostovi — ena najlepših sprehajalnih poti v Alpah.', 'Sotesko je odkril Josip Šlajpah leta 1891. Leseni hodniki so bili takrat revolucionarna turistična infrastruktura.', 'pot', 46.3858, 14.0775, NULL, 'gorenjska'),
  ('Slap Peričnik', 'Dvostopenjski slap v dolini Vrata — pod spodnjim slapom (52 m) je mogoče hoditi za vodo.', 'Spodnji slap Peričnik je edini v Triglavskem narodnem parku, za katerega se da hoditi zadaj — ledena stena pozimi je priljubljena med alpinisti.', 'slap', 46.4128, 13.8456, NULL, 'gorenjska'),
  ('Bohinjsko jezero', 'Največje naravno jezero v Sloveniji (318 ha) v srcu Triglavskega narodnega parka.', 'Pod jezerom teče ponikalnica — iz jezera odteka reka Savica, a del vode ponikne in se pojavi znova v Mostnici. Jezero je del UNESCO geoparkov.', 'jezero', 46.2842, 13.8617, NULL, 'gorenjska'),
  ('Velika planina', 'Največja visokogorska pastirska naselbina v Alpah (1500 m) z edinstvenimi pastirskimi kočami.', 'Naselbina je bila med 2. svetovno vojno popolnoma požgana in po vojni rekonstruirana. Koče imajo svojo posebno arhitekturno obliko, ki je drugje ne najdemo.', 'gora', 46.2956, 14.6403, NULL, 'gorenjska'),
  ('Pokljuka — biatlonski stadion', 'Visoka planota v TNP na 1350 m — svetovno znani biatlonski stadion, gozdne poti, mirna narava.', 'Pokljuka je ena redkih lokacij na svetu, kjer se odvija tekma Pokala sveta v biatonu sredi naravnega rezervata. Poleti je prizorišče pohodov med dišečimi smrekovimi gozdovi.', 'pot', 46.3383, 13.9764, NULL, 'gorenjska'),
  ('Kranjska Gora', 'Priljubljeno alpsko letovišče pri Vršiču in Planici — izhodišče za gore, smučanje, kolesarjenje.', 'Kranjska Gora je bila eno prvih zimskošportnih središč v Alpah, prizorišče alpskih tekmovanj že od leta 1937. V bližini je Ruska kapelica, zgrajena med 1. sv. vojno.', 'pot', 46.4844, 13.7839, NULL, 'gorenjska'),
  ('Planica — letalnica bratov Gorišek', 'Dom smučarskih rekordov in FIS Nordijskega SP — legendarna letalnica s 138-metrskim rekordnim skokom.', 'Sepp Bradl je leta 1936 tu prvič v zgodovini preskočil 100 m in šokiral svet. Danes skakalci dosegajo 250+ m — takratni rekord bi zdaj povprečen tekač zlahka premagal.', 'pot', 46.4942, 13.7297, NULL, 'gorenjska'),
  ('Storžič (2132 m)', 'Gorenjski simbol — pravilna piramida z razgledom na Karavanke, Kamniško-Savinjske Alpe in Julijske Alpe.', 'Storžič je po obliki eden najbolj prepoznavnih vrhov v Sloveniji. Njegovo ime izhaja iz besede ''storžek'' — majhen storžec smrekovega drevesa.', 'gora', 46.3978, 14.2717, NULL, 'gorenjska'),
  ('Golica (1836 m) — narcise', 'Gorenjski vrh v Karavankah, svetovno znan po čudovitem cvetenju narcis vsak april — morje belega cvetja.', 'Na Golici raste kar 26 vrst narcis. Cvetenje privabi vsako leto več kot 100.000 obiskovalcev. Narcise tu rastejo na naravnih travnikih brez kakršnekoli zasaditve.', 'gora', 46.4967, 13.9128, NULL, 'gorenjska'),
  ('Krvavec (1971 m)', 'Največje smučišče v bližini Ljubljane z gondolo iz Cerklja — poleti pohodništvo, kolesarjenje, razgledi.', 'Krvavec je dobil ime po rdeči barvi apnenca v skalah — po legendi pa po bitki med Turki in Slovenci, kjer je bila zemlja rdeča od krvi.', 'gora', 46.3031, 14.5281, NULL, 'gorenjska'),
  ('Slap Šum (Mostnica)', 'Najširši slap v Sloveniji (25 m) — Mostnica se prebija skozi ozko sotesko nad Bohinjsko Bistrico.', 'Mostnica teče skozi eno od najlepših sotesk v Sloveniji. V soteski je ''hudičev most'' — naravni lok nad vodo, po katerem so hodili pastirji.', 'slap', 46.3033, 13.8889, NULL, 'gorenjska'),
  ('Jasna jezero', 'Gorsko jezero pod Mojstrovko pri Kranjski Gori — bisernobistro vodo v alpski panorami.', 'Jezero je umetno — nastalo je po katastrofalnem zemeljskem plazu leta 1953. Kip Zlatoroga ob jezeru je postal eden prepoznavnih simbolov Kranjske Gore.', 'jezero', 46.4858, 13.7803, NULL, 'gorenjska'),
  ('Slap Martuljek', 'Dvojni slap v slikoviti soteski Martuljka — 60 m spodnji slap in 40 m zgornji slap v senci gozda.', 'Martuljška korita so eno redkih mest v Julijskih Alpah, kjer je mogoče videti divje koze (gamse) iz neposredne bližine. Dostop je po kratki markirani poti.', 'slap', 46.4817, 13.8219, NULL, 'gorenjska'),
  ('Zelenci — izvir Save Dolinke', 'Naravni rezervat z bistro, bisernobistro laguno — tu se pod skalo skrivnostno pojavi reka Sava Dolinka.', 'Voda, ki se tu pojavi, je padla kot dež ali sneg na Karavanke in teče pod zemljo več km preden privri na površje. Temperatura vode je konstantnih 6 °C skozi vse leto.', 'jezero', 46.5053, 13.7267, NULL, 'gorenjska'),
  ('Tamar dolina', 'Mirna alpska dolina pod Jalcem in Mojstrovko — konec asfaltne ceste in začetek prave divjine.', 'V Tamarju je planinarska koča iz leta 1908 — ena od prvih gorskih postojank v Julijskih Alpah. Poleti je baza za plezalce na Jalovec (2645 m).', 'pot', 46.5044, 13.7192, NULL, 'gorenjska'),
  ('Vršič (1611 m)', 'Najvišji cestni prelaz v Jugovzhodnih Alpah — 50 serpentin med Kranjsko Goro in Bovcem.', 'Cesto so med 1. sv. vojno zgradili ruski vojni ujetniki. Ko je pod plazom umrlo 300 delavcev, so zgradili Rusko kapelico pri Kranjski Gori kot spomin nanje.', 'gora', 46.4378, 13.7608, NULL, 'gorenjska'),
  ('Dolina Triglavskih jezer', 'Sedem ledeniških jezer na višini 1300–1996 m v srcu Triglavskega narodnega parka — ena najbolj divjih poti v Alpah.', 'Dolga jezera dobivajo svoje imena po barvi — Črno jezero, Dvojno jezero, Ledvica... Najgloblje Dvojno jezero meri 37 m. Pozimi so zamrznjena do 6 mesecev na leto.', 'jezero', 46.3242, 13.8208, NULL, 'gorenjska'),
  ('Ojstrica — razglediščni vrh nad Bledom', 'Razgledišče (611 m) nad zahodnim bregom Blejskega jezera — brezplačen razgled na jezero, otok in grad.', 'Ojstrica je med fotografski strokovnjaki znana kot ''Instagram točka'' za Bled — panorama je enaka fotografiji na starih avstrijskih razglednicah iz 19. stol.', 'gora', 46.3522, 14.0839, NULL, 'gorenjska'),
  ('Slap Pišnica', 'Slikovit slap nad Kranjsko Goro, dostopen po kratki poti — priljubljen za jutranjo sprehod.', 'Pišnica je pritok Save Dolinke, ki odteka iz Tamarja. Ime izhaja iz ''pisati'' — kar opisuje žuborenje vode čez kamenje.', 'slap', 46.4839, 13.7956, NULL, 'gorenjska'),
  ('Završnica (jezero)', 'Gorsko jezero nad Žirovnico — akumulacijsko jezero z razgledom na Karavanke in smaragdno vodo.', 'Jezero je nastalo z zajezitvijo gorskega potoka za hidroelektrarno leta 1914 — eno prvih hidroelektrarn v slovenskem alpskem prostoru.', 'jezero', 46.4089, 14.1375, NULL, 'gorenjska'),
  ('Soča — smaragdna reka', 'Kristalno zelena alpska reka med Bovcem in Tolminom — rafting, kajak, ribolov, pohodništvo.', 'Edinstvena smaragdno-turkizna barva Soče nastane zbog posebnega apnenca in drobnih suspendiranih delcev, ki razprašijo zeleno svetlobo. Barva se menja z letnimi časi.', 'pot', 46.3322, 13.5533, NULL, 'primorska'),
  ('Slap Boka', 'Najvišji slap v Sloveniji (106 m) — pada v enem samem skoku s stene pod Kaninom.', 'Boka je občasni slap — poleti skoraj presahne, po dežju ali topljenju snega pa postane mogočen. Spomladanska boka velja za eno najimpresivnejših naravnih prizorov v Alpah.', 'slap', 46.2928, 13.5672, NULL, 'primorska'),
  ('Slap Kozjak', 'Skrita dragulj Soške doline — 15 m slap pada v zamaknjeno turkizno tolmun v naravni jami.', 'Tolmun pod slapom je kot ampiteater — stene jame ga obdajajo s treh strani. Dostop po krajši poti ob Soči iz Napoleonovega mostu pri Kobaridu.', 'slap', 46.2347, 13.59, NULL, 'primorska'),
  ('Tolminska korita', 'Globoka soteska ob sotočju Tolminke in Zadlaščice — najtoplejša točka v Triglavskem narodnem parku.', 'Na dnu korit je temperatura za 10 °C višja kot na planoti — to je najtoplejše naravno mesto v TNP. Tu je skrita Medvedova glava — skala v obliki medvedjega obraza.', 'pot', 46.1828, 13.7197, NULL, 'primorska'),
  ('Idrija — rudnik živega srebra', 'UNESCO svetovna dediščina — 500-letni rudnik živega srebra, drugi največji na svetu, in rokodelsko mesto čipke.', 'Idrija je bila s 13% svetovne produkcije živega srebra eno najpomembnejših industrijskih mest 18. stol. Idrijska čipka je leta 2016 vpisana na UNESCO seznam nesnovne dediščine.', 'muzej', 45.9992, 14.0272, NULL, 'primorska'),
  ('Kanin (2587 m)', 'Najvišje smučišče v Sloveniji z gondolo iz Bovca — pozimi smučanje, poleti pohodništvo z razgledom na morje.', 'S Kanina je ob jasnem vremenu videti Jadransko morje in beneški Campanile. V podzemlju Kanina je eno globokih jam na svetu — Čehi so odkrili sistem do -1600 m.', 'gora', 46.3614, 13.5067, NULL, 'primorska'),
  ('Kobarid — muzej Soške fronte', 'Nagrajeni muzej o katastrofalni Soški fronti (1915–1917) — 12 bitk, milijoni žrtev, prelomna Kobaridska bitka.', 'Museum je leta 1993 prejel nagrado Sveta Evrope kot najboljši muzej v Evropi. Kobaridska bitka oktobra 1917 je navdihnila Hemingwaya za roman ''Zbogom, orožje''.', 'muzej', 46.2475, 13.5783, NULL, 'primorska'),
  ('Goriška Brda — vinorodni griči', 'Mediteransko podeželje z vinogradi, oljčniki in idiličnimi vasicami — Slovenija v miniaturi Toskane.', 'Brda ima enak klimatski pas kot Toskana in Bordo. Tukajšnja rebula in merlot sta cenjena po vsej Evropi. Vasica Šmartno je zaščitena kot kulturna dediščina.', 'pot', 45.9747, 13.5311, NULL, 'primorska'),
  ('Kluže trdnjava', 'Strateška trdnjava nad sotesko Koritnica pri Bovcu — stražarila je prelaz že v rimskih časih.', 'Trdnjava je bila v 16. stol. ključna obramba pred turškimi vpadi. Med 1. sv. vojno so jo Italijani in Avstrijci izmenično zasedali. Sedanja oblika je iz 18. stol.', 'muzej', 46.3411, 13.5483, NULL, 'primorska'),
  ('Slap Fratarica', 'Večstopenjski slap v globoki soteski nad Livškim Rovtom — dostopen po kratki markirani poti.', 'Fratarica je pritok Soče z neverjetno bistro vodo. Soteska je bila do 1990-ih praktično neznana — danes je ena priljubljenjih ''tajnih'' lokacij pohodnikov.', 'slap', 46.2575, 13.5447, NULL, 'primorska'),
  ('Kanal ob Soči', 'Vasica z monumentalnim starim mostom nad smaragdno Sočo — ena najfotografiranih lokacij Primorske.', 'Most je bil zgrajen leta 1890. Ko je poleti reka nizka, je voda pod mostom tako bistra, da je videti dno. Kraj je postal viralen na Instagramu po letu 2015.', 'muzej', 46.0889, 13.6583, NULL, 'primorska'),
  ('Partizanska bolnišnica Franja', 'UNESCO dediščina — popolnoma skrita partizanska bolnišnica v soteski Pasice med 2. svetovno vojno.', 'Bolnišnica je v 2 letih delovala ob reki Pasica, ki je bila 20 m globoko skrita v soteski. Nemci je niso nikoli odkrili kljub intenzivnemu iskanju. Zdravili so 578 ranjencev.', 'muzej', 45.9922, 14.1542, NULL, 'primorska'),
  ('Divje jezero (Idrija)', 'Kraški izvir z edinstveno kobaltnomodro vodo — eden vizualno najdramatičnejših izvirov v Evropi.', 'Divje jezero je eden najbogatejših vodnih izvirov v Alpah — ob visokem vodostaju izliva 100 m³ vode na sekundo. Natančna globina ni znana, potapljači so dosegli 160 m.', 'jezero', 46.0069, 14.0175, NULL, 'primorska'),
  ('Vipavska dolina', 'Mediteransko-celinska dolina z vinogradi, oljčniki in hruštovci — dom burje in odličnih vin.', 'Burja — severovzhodnik, ki piha skozi Vipavsko dolino, je uradno najhitrejši stalni veter v Evropi. Dosega hitrosti do 200 km/h in prevrača tovornjake na avtocesti.', 'pot', 45.8467, 13.9633, NULL, 'primorska'),
  ('Pot miru — Soška fronta', '102 km dolga pot skozi nekdanja bojišča 1. svetovne vojne ob reki Soči — od Rombona do Jadrana.', 'Vzdolž poti je ohranjenih 1000+ zgodovinskih točk — strelski jarki, bunkerji, bolnišnice, kapelice. Pot je priljubljena pri kolesarjih in je del Evropske mreže kulturnih poti.', 'pot', 46.1992, 13.6567, NULL, 'primorska'),
  ('Jezero Most na Soči', 'Turkizno akumulacijsko jezero v soteski Soče — ribolov na soško postrv, veslanje, promenada.', 'Pod gladino jezera so potopljeni ostanki prazgodovinske naselbine situlske kulture (800–300 pr. n. št.). Arheologi so jih preučevali preden je jez zajezil vodo.', 'jezero', 46.1417, 13.8033, NULL, 'primorska'),
  ('Sabotin (609 m)', 'Razgledni vrh nad Novo Gorico in Gorico — panorama na Goriška Brda, Soško ravnico in Alpe.', 'Sabotin je bil eno najtežjih vojnih gora med Soško fronto — Italijani so ga po 29 neuspelih napadih zavzeli z 10.000 vojaki avgusta 1916. Na vrhu je vojni muzej na prostem.', 'gora', 45.9753, 13.6447, NULL, 'primorska'),
  ('Piran — staro mestno jedro', 'Ohranjena venetska arhitektura na rtu z razgledom na Jadransko morje — eden najlepših jadranskih mest.', 'Piran ima le 4.000 prebivalcev a ima kar 300 kulturnih spomenikov. Tartinijev trg je po obliki ena najlepših ovalneh elips med jadranskimi trgi. Rimski zid obkroža staro mesto.', 'muzej', 45.5281, 13.5694, NULL, 'primorska'),
  ('Sečoveljske soline', 'Naravni rezervat in park z aktivno pridobivanjem morske soli — ornitološki raj z 280+ vrstami ptic.', 'V solinah se sol pridobiva enako kot pred 700 leti — brez strojev, samo z lesenim orodjem. Fleur de sel iz Sečovelj je ena najdražjih soli na svetu.', 'pot', 45.4819, 13.6172, NULL, 'primorska'),
  ('Lipica — Kobilarna', 'Rojstni kraj lipicanske pasme — jahalne predstave belih konjev od leta 1580 v senčnatem parku.', 'Lipicanec je nastajal 450 let — mešanica španskih, arabskih in berberskih pasem. Žrebički so rojeni temni in posvetle šele pri 7 letih. Bela barva je bila plemenita barva habsburškega dvora.', 'muzej', 45.7044, 13.8461, NULL, 'primorska'),
  ('Strunjan — naravni rezervat', 'Najdaljši strmi klif na vzhodni obali Jadrana (80 m), laguna, solinarstvo — mirna alternativa Piranu.', 'V Strunjanski laguni rastejo ribičke košare in so se letos vrnile vidre — vrsta, ki je bila na tem območju iztrebljena 100 let. Klif je geološko edinstvena formacija fliša.', 'pot', 45.5311, 13.6083, NULL, 'primorska'),
  ('Portorož — promenada', 'Turistično središče slovenskega obmorja — plaže, kazino, spa centri, letališče.', 'Portorož ima mikroklimo zahvaljujoč Strunjanskim solinam in gozdu — povprečno 2400 ur sonca na leto, enako kot Nica. Prvič je bil turistično razvit leta 1885.', 'pot', 45.5017, 13.5942, NULL, 'primorska'),
  ('Izola — staro mestno jedro', 'Nekdanji otočič, danes polotok z lepim starim mestom in pristaniščem — manj turistično od Pirana.', 'Izola je bila do 17. stol. resnični otok — nasuta cesta jo je leta 1826 povezala z obalo. V mestu je ena najstarejših olivnih nasadov v Mediteranu — drevo staro 1500 let.', 'muzej', 45.5397, 13.6631, NULL, 'primorska'),
  ('Škocjanske jame', 'UNESCO svetovna dediščina — 160 m globoka Martelova dvorana in eden največjih podzemnih kanjonov na svetu.', 'Martelova dvorana je tako velika, da bi v njej stala Eifflov stolp — 160 m višine, 300 m dolžine. Podzemna reka Reka je erozijsko preoblikovala Kras milijone let.', 'jama', 45.6642, 13.9961, NULL, 'notranjska'),
  ('Predjamski grad', 'Renesančni grad vgrajen v 123 m visoko skalno steno — dom viteza Erazma Predjamskega.', 'Erazem Predjamski je grad branil 1 leto (1484) s pomočjo tajnega tunela skozi skalo — dokler ga niso ujeli med ''ranljivo'' potrebo. Grad je eden od Guinnessovih rekordov.', 'muzej', 45.8153, 14.1269, NULL, 'notranjska'),
  ('Postojnska jama', 'Najdaljša turistična jama v Evropi (24 km) — dom človeške ribice Proteusa in edinstven podzemni svet.', 'Proteus anguinus — človeška ribica — živi samo v Postojnski jami in podobnih kraških jamah. Slepa je, živi do 100 let in se pari le vsakih 12 let. Je edini jamski vretenčar v Evropi.', 'jama', 45.7833, 14.2019, NULL, 'notranjska'),
  ('Cerkniško jezero', 'Največje prehajajoče (periodično) jezero v Evropi — pozimi jezero z 26 km², poleti travnik s cvetjem.', 'Jezero izgine ker voda odteče skozi ponore v karst — podobno kot v kopalni kad. Celoten cikel (napolnjevanje in praznenje) se ponovi večkrat na leto, odvisen od padavin.', 'jezero', 45.7833, 14.3667, NULL, 'notranjska'),
  ('Rakov Škocjan', 'Naravni park z dvema naravnima kamnitima mostovoma — ponikalnica Rak skozi kraški amfiteater.', 'Mali in Veliki naravni most sta nastala z ugreznjanjem jame — strop se je porušil, stranski steni pa sta ostali. Gre za enega redkih naravnih mostov iz apnenca v Evropi.', 'pot', 45.78, 14.1492, NULL, 'notranjska'),
  ('Snežnik (1796 m)', 'Najvišji nealpski vrh Slovenije z razgledom na Jadransko morje, Alpe in Hrvaško Primorje.', 'Snežnik je edina gora v Sloveniji, ki ni del Alp — je del Dinaridov. Na vrhu so ohranjene snežne naprave za umetno zasneževanje iz 1950-ih, ki pa niso več v uporabi.', 'gora', 45.5919, 14.4431, NULL, 'notranjska'),
  ('Križna jama', 'Jama z 22 podzemnimi jezeri — edinstven svet kristalno bistrega podzemnega zrcala.', 'V Križni jami so odkrili okostnjake jamskega medveda (Ursus spelaeus), ki je izumrl pred 28.000 leti. Ogled jame z barko po podzemnih jezerih je edinstven izkušnja.', 'jama', 45.7553, 14.5308, NULL, 'notranjska'),
  ('Nanos (1313 m)', 'Kraška planota z razgledom na Vipavsko dolino, Jadransko morje in Furlanski nižini.', 'Nanos je bil strateška točka že Rimljanov — na vrhu so bili ostanki rimskega signalnega stolpa. Pozimi je Nanos med najbolj vetrovno točkami v Evropi (burja do 150 km/h).', 'gora', 45.7697, 14.0517, NULL, 'notranjska'),
  ('Planinska jama', 'Jama z največjo podzemno reko v Evropi — Unica teče skozi jamo in jo je mogoče obiskati z barko.', 'Planinska jama je skupaj s Postojnsko jamo del istega jamskega sistema — dolg 34 km. Reka Pivka ponikne pri Postojni in se pojavi 10 km naprej kot Unica v Planini.', 'jama', 45.8142, 14.2203, NULL, 'notranjska'),
  ('Grad Snežnik', 'Romantičen lovski dvorec sredi pragozdov Snežniške planote — popolnoma ohranjena notranjost iz 19. stol.', 'Grad so zgradili Uskoki v 16. stol., a je postal rezidenca nemškega princa Windischgrätz v 19. stol. Vsa pohištvena oprema je originalna — grad je bil ''zaprt v jantarju'' od 1945.', 'muzej', 45.565, 14.4372, NULL, 'notranjska'),
  ('Vremščica (1027 m)', 'Planinska gora na Krasu z razgledom na Trst, Jadransko morje in Tržiški zaliv.', 'Zaradi nizke lege in bližine morja je Vremščica ena redkih gora v Evropi, s katere je videti morje na dveh straneh — Tržaški zaliv in delno Kvarner.', 'gora', 45.7422, 13.9267, NULL, 'notranjska'),
  ('Ljubljanski grad', 'Renesančni grad na griču nad prestolnico — muzej, razgledna terasa, funikular, prireditve.', 'Grad je star 900 let, a je bil večkrat porušen in obnovljen. Zakladnica na gradu hrani originalni Valvasorjev rokopis Slave vojvodine Kranjske — enciklopedije iz 1689.', 'muzej', 46.0487, 14.5081, NULL, 'osrednjeslovenska'),
  ('Tromostovje — Prešernov trg', 'Srce Ljubljane — tri mostovi arhitekta Plečnika, Prešernov trg in vrvež kavarn ob reki Ljubljanici.', 'Plečnik je Tromostovje zasnoval z dodajanjem dveh stranskih mostov k že obstoječemu (1929–1931). Skupaj so edinstven primer tripartitne promenada v Evropi.', 'muzej', 46.0514, 14.5064, NULL, 'osrednjeslovenska'),
  ('Šmarna gora (669 m)', 'Ljubljansko izletniško srce — priljubljena pohod destinacija z gostilnico na vrhu in razgledom na Alpe.', 'Šmarno goro vsako jutro obišče 2000+ tekačev in pohodnikov — je med 10 najbolj frekventnimi gorami v Evropi glede na površino. Cerkvica sv. Marjete na vrhu je iz 15. stol.', 'gora', 46.1442, 14.4703, NULL, 'osrednjeslovenska'),
  ('Arboretum Volčji Potok', 'Najlepši botanični vrt v Srednji Evropi (85 ha) — spomladi naravnost osupljivo cvetenje tulipanov in češenj.', 'Arboretum je bil zasebni vrt grofov Souvan, ki so v 19. stol. sadili eksotične drevesne vrste z vseh koncev sveta. Danes rastejo tu drevesa iz 6 celin.', 'pot', 46.1919, 14.6153, NULL, 'osrednjeslovenska'),
  ('Tivoli — mestni park', 'Največji park v Ljubljani (5 km²) — razstavna promenada, ribnik, gozd, Plečnikova aleeja.', 'Tivoli park je vzorčen po vzoru pariškega Bulonjskega gozda, zasnoval ga je župan Ivan Hribar v 1900-ih. V parku je ribnik, kjer se pozimi drsajo Ljubljančani.', 'pot', 46.0553, 14.4958, NULL, 'osrednjeslovenska'),
  ('Grad Bogenšperk', 'Renesančni grad pri Šmartnem — dom Janeza Vajkarda Valvasorja, avtorja enciklopedije Slava vojvodine Kranjske.', 'Valvasor je porabil vso premoženje za pisanje Slave vojvodine Kranjske (1689) — 3532 strani, 528 bakrorezov. Knjiga je bila tako draga, da je bil Bogenšperk prisiljen prodati.', 'muzej', 45.9361, 14.9194, NULL, 'osrednjeslovenska'),
  ('Krim (1107 m)', 'Razgledna gora nad Barjem — razgled na Alpe, Notranjsko in Ljubljansko kotlino.', 'Na Krimu je bila med 2. sv. vojno skrita partizanska tiskarna — tu so tiskali ilegalne časopise in letake. Na vrhu sta kapela in planinski dom.', 'gora', 45.8808, 14.4714, NULL, 'osrednjeslovenska'),
  ('Stari grad Kamnik', 'Ruševine gradu nad Kamnikom z impresivnim razgledom na Kamniško-Savinjske Alpe in Ljubljansko kotlino.', 'Mali grad v Kamniku ima dvojno kapelico — zgornji in spodnji kor — edinstven romanski arhitekturni element v Sloveniji iz 12. stol. Grad je bil v 13. stol. sedež gospodov Kamniku.', 'muzej', 46.2233, 14.6106, NULL, 'osrednjeslovenska'),
  ('Sv. Primož nad Kamnikom', 'Romarska cerkvica visoko nad Kamnikom z mozaičnimi freskami — priljubljena nedeljska izletniška točka.', 'Cerkvica stoji na 1065 m in ima izjemen razgled. Do nje pelje 1h pot iz Stahovice — mimo votline z ledenimi stalaktiti (Ledena jama) ki so vidni poleti.', 'muzej', 46.2256, 14.5722, NULL, 'osrednjeslovenska'),
  ('Kamniška Bistrica (izvir)', 'Planinarski dom in kapela ob izviru Kamniške Bistrice — izhodišče za Planjavo, Brano in Kamniško sedlo.', 'Izvir Kamniške Bistrice je kraški — voda pride iz podzemlja po sistemu kanalov v Kamniških Alpah. Temperatura je konstantnih 4 °C skozi vse leto.', 'pot', 46.2939, 14.5953, NULL, 'osrednjeslovenska'),
  ('Iški vintgar', 'Manj znana soteska reke Iške pri Igu — divji svet z naravnimi tolmuni in slapovi.', 'Iški vintgar je geološko enako star kot Blejski, a ga obišče stokrat manj turistov. V soteski so ohranjeni rimski kamni — mlin ob Iški je bil rimski mejnik.', 'pot', 45.8917, 14.3903, NULL, 'osrednjeslovenska'),
  ('Grad Turjak', 'Mogočni renesančni grad nad Turjakom — ena najboljše ohranjenih grajskih trdnjav v osrednji Sloveniji.', 'Turjak so posedovali Auerspergi — ena najpomembnejših plemiških družin Kranjske, ki je imela v lasti 160 gradov po Evropi. Med 2. sv. vojno so partizani grad do tal požgali.', 'muzej', 45.9056, 14.6194, NULL, 'osrednjeslovenska'),
  ('Rožnik (394 m)', 'Gozdnat hrib nad Tivolijem — Ivan Cankar je tu pisal in živel, priljubljen sprehajalni gozd Ljubljančanov.', 'Ivan Cankar je živel v koči na Rožniku (Cankarjev hram) in tu napisal nekatera svoja najpomembnejša dela. Njegova koča je ohranjena kot muzej.', 'gora', 46.0547, 14.4772, NULL, 'osrednjeslovenska'),
  ('Šentjošt nad Horjulom', 'Razgledna točka nad Polhograjskim hribovjem — priljubljena kolesarska in pohodniška destinacija.', 'Iz Šentjošta je razgled na Ljubljana, Triglav in Snežnik — tri geografsko ključne točke Slovenije na enkrat. Gostilna na vrhu je znana po domači hrani.', 'gora', 46.0972, 14.3522, NULL, 'osrednjeslovenska'),
  ('Logarska dolina', 'Ena najlepših alpskih ledeniških dolin v Evropi — naravni park s slapovi in gorami.', 'Logarska dolina je bila ''odkrita'' za turizem šele v 1970-ih. Pred tem so dolino obiskovali samo planinci. Dolina je tako ohranjena, ker nima gorske avtoceste.', 'pot', 46.3975, 14.6247, NULL, 'savinjska'),
  ('Slap Rinka', 'Mogočni 90 m visok slap ob vhodu v Logarsko dolino — eden od treh največjih slapov v Savinjskih Alpah.', 'Rinka je bila motivacija za reševanje Logarske doline pred industrijskim razvojem v 1970-ih. Kmetje so slap opisali državnim uradnikom in to je prepričalo oblast za naravni park.', 'slap', 46.4039, 14.6022, NULL, 'savinjska'),
  ('Celjski grad', 'Največji ohranjen grad v Sloveniji na griču nad Celjem — dom mogočnih grofov Celjskih, ki so vladali kot kralji.', 'Celjski grofje so bili v 15. stol. rivalji Habsburžanov in so vladali ozemlju od Jadrana do Donave. Imeli so pravico kovati denar in bili zadnji neodvisni vladarski rod na Slovenskem.', 'muzej', 46.2367, 15.2636, NULL, 'savinjska'),
  ('Robanov kot', 'Mirna alpska dolina ob zgornji Savinji — izhodišče za Olševo, Raduho in Logarski prehod.', 'Robanov kot ima le 6 stalnih kmetij — ena od najredkeje poseljenih alpskih dolin v Alpah. Kmetje živijo brez turizma in prodajajo samo domače sir in meso.', 'pot', 46.3892, 14.6706, NULL, 'savinjska'),
  ('Mozirski gaj', 'Nagrajeni botanični vrtni park z 20.000 rastlinami ob Savinji — posebej spektakularen v cvetnih sezonah.', 'Mozirski gaj je za male dmenzije (7 ha) eden najgosteje zasajenih botaničnih vrtov v Evropi. Vsako leto ga obišče 250.000 obiskovalcev — več kot ima Mozirje mieszkov.', 'pot', 46.3392, 14.9628, NULL, 'savinjska'),
  ('Šmartinsko jezero', 'Rekreacijsko jezero pri Celju — kopanje, kajak, kolesarjenje in tek po obalni poti.', 'Jezero je nastalo z zajezitvijo Reke in je bilo odprto za rekreacijo šele v 1980-ih. Naravni rezervat na severnem bregu je dom 140+ vrst ptic — naravni filtrirni sistem.', 'jezero', 46.2014, 15.3397, NULL, 'savinjska'),
  ('Slap Orglice', 'Slap v obliki orgelskih pip pri Mozirju — kratka pot od ceste skozi bukov gozd.', 'Orglice dobijo ime po posebnem zvoku, ki nastane ko voda teče čez apnenčaste pipe — zvok je res podoben organskim tonom, posebej po dežju.', 'slap', 46.3614, 14.9472, NULL, 'savinjska'),
  ('Velenje — grad in jezero', 'Grad nad rudnikovskim mestom Velenje in umetno jezero z rekreacijskimi možnostmi.', 'Velenje je bilo v Jugoslaviji ''vzorčno socialistično mesto'' — zgrajeno od nič z rudnikovskim denarjem. Grad je bil pred tem v ruševinah in so ga obnovili v 1950-ih.', 'muzej', 46.3586, 15.1092, NULL, 'savinjska'),
  ('Golte — gondola', 'Gondola iz Mozirja na Golte (1464 m) — smučišče poleti postane gorsko kolesarsko in pohodniško središče.', 'Z Golt je razgled na celotno Savinjsko dolino in na Kamniško-Savinjske Alpe. V napajalni postaji gondole je razstavljen električni motor iz prve gondole iz leta 1971.', 'gora', 46.2986, 14.8731, NULL, 'savinjska'),
  ('Olševa (1929 m)', 'Razgledni vrh na meji z Avstrijo z dolgimi smučarskimi progami in panoramo na Savinjske Alpe.', 'Olševa ima posebno botanično vrednost — tu raste kar 1000 vrst rastlin vključno z redkimi alpskimi orhidejami. Ime izhaja iz besede ''olša'' — jelša.', 'gora', 46.5028, 14.7525, NULL, 'koroska'),
  ('Rudnik Mežica', 'Podzemno adrenalinsko doživetje — vožnja z vlakcem skozi 1 km podzemnih rovov nekdanjega svinca in cinkovega rudnika.', 'Rudnik je deloval od 17. stol. do 1994. Skupaj ima 1000 km rovov — toliko kot Ljubljana do Madrida. Poleti se rovi spremenijo v edinstveno podzemno kolesarsko stezo.', 'jama', 46.5222, 14.8528, NULL, 'koroska'),
  ('Raduha (2062 m)', 'Strma koroška gora nad Logarsko dolino — eden najtežjih vzponov v Savinjskih Alpah.', 'Na Raduhi je odkrita kapelica sv. Urbana iz 18. stol., ki so jo vzdrževali pastirji. Vrh je bil pred 1850 poznan po lovu na kozoroga — danes je le kak srnjak.', 'gora', 46.4306, 14.7478, NULL, 'koroska'),
  ('Šumik — slap', 'Najlepši koroški slap (25 m) med bukovim gozdom — markirana pot iz Mežice, primerna za vse.', 'Šumik se pojavi samo po dežju — je tipičen ''epizodni'' slap, ki v suhi sezoni skoraj presahne. Po obilnem dežju pa postane osupljivo impresiven.', 'slap', 46.5069, 14.875, NULL, 'koroska'),
  ('Topla dolina', 'Skrita alpska dolina nad Mežico — divji travniki, planine in koroška tišina brez množic.', 'Topla je tipičen primer odmaknjene koroške doline z aktivnim kmetijskim izročilom. Poleti je dolina polna košenine — posušena trava za zimsko živino.', 'pot', 46.5381, 14.8994, NULL, 'koroska'),
  ('Peca (2126 m)', 'Simbol Koroške — masivna gora na meji z Avstrijo z razglednim planotastim vrhom.', 'Na Peci je bil leta 1921 prvi alpski kolesarski maraton na Slovenskem. Pod goro je rudnik z lastnim muzejom — jama je del istega geologijo kot Mežica.', 'gora', 46.5111, 14.9197, NULL, 'koroska'),
  ('Ptujski grad', 'Najstarejše slovensko mesto z mogočnim gradom — dom pustu Kurenta in bogatega muzeja.', 'Ptuj je starejši od Rima — settlement na griču je obstajal 5000 let. Kurenti so bil poganski simbol spomladi in plodnosti, ki je premagoval zimo — živi v Ptujskemu karnevalu.', 'muzej', 46.4203, 15.8692, NULL, 'stajerska'),
  ('Stara trta — Maribor', 'Najstarejša žlahtna trta na svetu (400+ let) v starem Mariboru — Guinnessov rekord, modra frankinja.', 'Trta rodi vsako leto 35–55 kg grozdja iz katerega naredijo samo 100 steklenic posebnega vina. Buteljke so darila državnikom — prejeli so jih Obama, Putin in britanska kraljica.', 'muzej', 46.5531, 15.6483, NULL, 'stajerska'),
  ('Pohorje — smučišče in narava', 'Obsežna gozdnata planota nad Mariborom — smučišče, gorsko kolesarjenje, pohodništvo, terme.', 'Pohorje je ''lena'' gora — brez strmih sten, le položni hribi. Pod površjem leži edinstveni crni granit pohoritu — kamen, ki ga drugje v Alpah ni.', 'gora', 46.4867, 15.4044, NULL, 'stajerska'),
  ('Mariborski grad', 'Renesančni grad v centru Maribora z Regionalnim muzejom — bogata zbirka o zgodovini Štajerske.', 'Grad je bil zgrajen kot obramba pred Turki. Med oblego leta 1532 je Maribor vzdržal turški napad z le 2000 možmi proti 300.000 Turkov — zahvaljujoč trdnim zidovom.', 'muzej', 46.5578, 15.6461, NULL, 'stajerska'),
  ('Ptujsko termalno jezero', 'Naravno termalno jezero ob reki Dravi pri Ptuju — kopanje, vodni športi, termalni park.', 'Termalna voda v tem jezercu izhaja iz naravnih geotermalnih izvirov, ki so jih odkrili med vrtanjem za nafto v 1950-ih. Temperatura vode je 35–38 °C skozi vse leto.', 'jezero', 46.3756, 15.8844, NULL, 'stajerska'),
  ('Rogaška Slatina', 'Najstarejše slovensko zdravilišče z Donatom Mg — edinstven magnezijev izvir, ki je priljubljen v 40+ državah.', 'Rogaška Slatina ima izvir s 15.000 mg/L magnezija — dvajsetkrat več kot normalna mineralna voda. Izvirno steklenico je leta 1803 pokušal cesar Napoleon in jo pohvalil.', 'pot', 46.2269, 15.6361, NULL, 'stajerska'),
  ('Jeruzalem — vinorodni griči', 'Vinorodni griči severovzhodne Štajerske — malvazija, šipon in laški rizling ter panoramske poti med vinogradi.', 'Ime Jeruzalem naj bi dal kraj crusader vitez, ki je bil tako navdušen nad krajem, da ni šel naprej. Tukajšnji laški rizling je bil v 19. stol. eden najdražjih vin v Avstriji.', 'pot', 46.4953, 16.1939, NULL, 'stajerska'),
  ('Haloze — vinorodni griči', 'Valoviti štajerski griči z vinogradi in zaselki — manj znana, a čudovita pokrajina med Dravo in Sotlo.', 'Haloze so ena redkeje poseljenih območij v Sloveniji — gosto porasli z vinogradi, ki jih negujejo isti rodovi kmetov kot pred 200 leti. Sivi pinot iz Haloz je mednarodno priznan.', 'pot', 46.3028, 15.9175, NULL, 'stajerska'),
  ('Piramida — Maribor', 'Hrib z vinogradi sredi Maribora — razgled na mesto, Pohorje in Dravsko polje, vzpetina s turistično pivnico.', 'Piramida je edinstvena — hrib sredi mesta z aktivnimi vinogradi. Mariborčani jo vzpenjajo vsak dan za vadbo. Na vrhu so ostanki rimske postojanke iz 1. stol.', 'gora', 46.5597, 15.6564, NULL, 'stajerska'),
  ('Kozjak soteska', 'Dramatična soteska reke Drave med Framom in Mariborom — pohodniška pot ob reki.', 'Soteska je bila nekoč neprehodni naravni mejnik — danes je pohodniška pot, a reka je še vedno divja. V soteski gnezdi bele štorklje in vodomec.', 'pot', 46.4875, 15.7553, NULL, 'stajerska'),
  ('Štatenberg — baročni dvorec', 'Baročni dvorec sredi naravnega parka v Halozah — obnovljena rezidenca z zdravilnimi zeliščnimi vrtovi.', 'Dvorec je bil v 19. stol. last Windischgrätzev — iste plemiške rodbine, ki je imela grad Snežnik. Med 2. sv. vojno je bil tu štab partizanov.', 'muzej', 46.3758, 15.7139, NULL, 'stajerska'),
  ('Grad — grad (Pomurje)', 'Mogočna romanska utrdba na vrhu hriba — eden redkih dobro ohranjenih gradov iz 12. stol. v Prekmurju.', 'Grad je edina romanska utrdba v Prekmurju — regiji, ki je bila 900 let pod Madžari in je ohranila svojo posebno identiteto. Razgled seže do Avstrije in Hrvaške.', 'muzej', 46.7856, 16.2394, NULL, 'pomurska'),
  ('Bogojina — Plečnikova cerkev', 'Arhitekturni biser prekmurske ravnine — Jože Plečnik je prenovil vaško cerkev (1924–1927) v modernistično remek-delo.', 'Plečnik je cerkveno zvonico prestavil in ji dodal čebulasto kupolo ter lončeno keramiko — unikat v slovenskem sakralnem prostoru. Ker so imeli le malo denarja, je Plečnik vzel projekt brezplačno.', 'muzej', 46.6989, 16.4394, NULL, 'pomurska'),
  ('Terme Moravske Toplice', 'Naravni termalni vrelec (72 °C) — eden najmočnejših termalnih izvirov v Evropi, kopalni park s termino toplo vodo.', 'Izvor so odkrili naključno med vrtanjem za nafto leta 1960. Voda izhaja iz globine 1500 m in ima temperaturo 72 °C — edina tako vroča geotermalna voda v Sloveniji.', 'pot', 46.6833, 16.2167, NULL, 'pomurska'),
  ('Bukovniško jezero', 'Termalno jezero z najtoplejšo vodo za kopanje v severovzhodni Sloveniji — šotorišče, ribištvo, sprehodi.', 'Jezero je nastalo kot gramoznica — ko so vzeli gramoz za gradnjo, se je kotanja napolnila z geotermalno vodo. Temperatura je 28–32 °C celo leto.', 'jezero', 46.7128, 16.0839, NULL, 'pomurska'),
  ('Filovci — vas belih štorkelj', 'Prekmurska vas z eno največjih kolonij belih štorkelj v Srednji Evropi — do 30 gnezd na strehah.', 'Štorklje so v Filove prišle nazaj po 50 letih v 1990-ih zahvaljujoč varstvenim programom. Vrnitev je bila slučajno — eden para je pristala na stari dimni in se ni hotel preseliti.', 'pot', 46.7558, 16.1739, NULL, 'pomurska'),
  ('Martjanci — gotske freske', 'Prekmurska cerkvica s čudovitimi gotskimi freskami Janeza Aquile iz 14. stol. — skrit biser.', 'Aquila je naslikal freske v vsaj 10 cerkvah po Prekmurju in Madžarski — bil je potujoči freskant 14. stol. Martinjanški ciklus velja za najboljše ohranjenega.', 'muzej', 46.7017, 16.4106, NULL, 'pomurska'),
  ('Lendava — grad in sinagoga', 'Večetnično mesto z gradom, sinagogo in mešeto — simbol prekmurske strpne tradicije.', 'Lendava je edino slovensko mesto, ki ima hkrati grad, sinagogo (iz 1866, danes galerija) in mošejo (islamski center). To odraža bogato zgodovino madžarsko-judovske kulture.', 'muzej', 46.5544, 16.4511, NULL, 'pomurska'),
  ('Goričko — naravni park', 'Naravni park s tipično prekmursko pokrajino — mlinčki na potokih, mlini, vinogradi in belokranjski zidanici.', 'Goričko ima enega največjih deležev ekoloških kmetij v Evropi — več kot 40% kmetov kmetuje brez kemikalij. V parku gnezdita orel in crna štorklja.', 'pot', 46.85, 16.0333, NULL, 'pomurska'),
  ('Trboveljski dimnik (360 m)', 'Tretji najvišji dimnik v Evropi — industrijski simbol Zasavja in enega od zaščitenih kulturnih mentioned.', 'Dimnik je bil zgrajen leta 1976 za trboveljsko termoelektrarno in je višji od Eifflovega stolpa (324 m). Ko so ga zgradili, je bil tretji najvišji objekt v Evropi.', 'muzej', 46.1533, 15.0503, NULL, 'zasavska'),
  ('Radeče — sotočje Sava-Savinja', 'Slikovito sotočje rek Save in Savinje z zgodovinskim mestnim centrom in promenado.', 'Na sotočju pri Radečah je bila v rimskih časih obmejnei postaja Ad Savum. Najdbe kažejo na aktiven rimski ribolov — mreže z uteži so odkopali ob gradnji.', 'pot', 46.07, 15.1811, NULL, 'zasavska'),
  ('Zagorje — muzej in rudnik', 'Mesto premogovništva v Zasavju — muzej premogovnika in obnovljeni industrijski park.', 'Zagorski premogovnik je bil eden prvih premogovnikov v Avstriji (1757). Premogovništvo je oblikovalo Zasavje — rudniki so dali delu Slovencev ''proletarsko'' identiteto.', 'muzej', 46.1331, 14.9967, NULL, 'zasavska'),
  ('Brežice — Posavski muzej', 'Renesančni grad z magnificentno Viteško dvorano — eden najbogatejših in najlepših gradov v Sloveniji.', 'Viteška dvorana v Brežicah je med redkimi primeri v Evropi, kjer je bogato poslikana celotna stropna površina — 1000 m² fresk iz 1660-ih je popolnoma ohranjena.', 'muzej', 45.9058, 15.5906, NULL, 'posavska'),
  ('Terme Čatež', 'Največji termalni park v Srednji Evropi na bregovih reke Save — termalni bazeni, glamping, hoteli.', 'Terme Čatež imajo 5 ha bazenskih površin z vodo med 32–36 °C — več kot kateri koli drug term v Avstriji. Letno jih obišče 1.3 milijona gostov.', 'pot', 45.8911, 15.6044, NULL, 'posavska'),
  ('Kostanjevica na Krki', 'Najmanjše slovensko mesto na otočku v reki Krki — cistercijanska opatija in galerija Forma Viva.', 'Kostanjevica je obtočena z reko Krko — resnični otoček, dostopen le po dveh mostičih. Cistercijanska opatija hrani eno od redkih romanskih kloster v Srednji Evropi.', 'muzej', 45.8463, 15.4583, NULL, 'posavska'),
  ('Bizeljsko — repnice', 'Edinstvene vinske kleti vkopane v puhlico — mehko geološko formacijo, ki jo je mogoče izkopavati ročno.', 'Puhlica (loess) je toliko mehka, da so jo kmetje vkopavali sami brez opreme. Repnice — kot so kleti — vzdržujejo konstantno temperaturo 10–12 °C celo leto, idealno za vino.', 'jama', 45.9261, 15.6889, NULL, 'posavska'),
  ('Grad Rajhenburg (Brestanica)', 'Mogočni grad nad Savo — benediktinski samostan, med 2. sv. vojno zbirno taborišče, danes center za starejše.', 'V Rajhenburg je bil leta 1941 eden od prvih koncentracijskih taborišč v Jugoslaviji. Nemci so tu zbirali Slovence pred deportacijo. Danes je kraj spomina in miru.', 'muzej', 46.0181, 15.5008, NULL, 'posavska'),
  ('Mokrice — grad', 'Renesančni grad z golfiškim igriščem v parku — eden redkih hotelskih gradov v Sloveniji.', 'Mokrice so bile last Windischgrätzev in nato Habsburžanov — cesarica Marija Terezija je tu večkrat prenočila. Golf igrišče je nastalo v 1990-ih in je med bolj slikovitimi v Evropi.', 'muzej', 45.8397, 15.6467, NULL, 'posavska'),
  ('Otočec — grad na rečnem otoku', 'Edini rečni grad v Sloveniji na otočku v Krki — hotel, golf, promenada ob reki.', 'Grad je bil v 15. stol. last Celjskih grofov. Danes je hotel s 5 zvezdicami — med elitnimi gosti so bili Tito, Churchill in kralj Španije. Dostopen le po mostu nad reko.', 'muzej', 45.8731, 15.2347, NULL, 'dolenjska'),
  ('Izvir Krke', 'Kraški izvir reke Krke — jama z vodo, kapelica sv. Janeza in romantičen vrt nad izvirom.', 'Izvir Krke je eden najlepših kraških izvirov v Dinaridih. Voda izvira iz sistema podzemnih kanalov pod Krško planoto in ima temperaturo 10 °C skozi vse leto.', 'jezero', 45.8244, 14.8747, NULL, 'dolenjska'),
  ('Žužemberk — grad in slapovi', 'Delno obnovljeni grad nad reko Krko z lepo promenado ob reki in manjšimi slapovi.', 'Žužembeški grad je bil v 16. stol. sedež turških obrambnih ukrepov. Ob gradu je tehniški muzej z mitom o Žužemberku — da je bil tu prvi mlin z drsečim kamnom v Evropi.', 'muzej', 45.8344, 14.9289, NULL, 'dolenjska'),
  ('Pleterje — kartuzijanski samostan', 'Edini živi kartuzijanski samostan v Sloveniji — menihi živijo v popolni tišini in prodajajo domača žganja.', 'Kartuzijanci so red menihovnika ki zahteva absolutno tišino — menihi ne govorijo razen pri skupnih molitvah in enkrat tedensko. Samostan so ustanovili Celjski grofje leta 1407.', 'muzej', 45.8256, 15.2094, NULL, 'dolenjska'),
  ('Stična — cistercijanska opatija', 'Najstarejši cistercijanski samostan v Sloveniji (1136) — romansko-gotska arhitektura, muzej in knjižnica.', 'Stična je eden od 8 prvih cistercijanskih samostanov izven Francije, ki so še v delovanju. V knjižnici je 10.000 knjig, od tega 500 rokopisov iz 12. stol. — neprecenljiva dediščina.', 'muzej', 45.9494, 14.8461, NULL, 'dolenjska'),
  ('Terme Dolenjske Toplice', 'Naravni termalni izvir — wellness, zdravilišče in jahanje v idiličnem gozdu Dolenjske.', 'Dolenjske Toplice so imele zdravilno vrelec znan že v rimski dobi. Habsburžani so jih uredili v zdravilišče v 18. stol. Zdravili so se tu plemiči iz vse monarhije.', 'pot', 45.7553, 15.0581, NULL, 'dolenjska'),
  ('Muljava — Jurčičev kraj', 'Vasica Josipa Jurčiča — rojstni kraj prvega slovenskega romanopisca, ki je tu napisal ''Deseti brat''.', 'Jurčičev ''Deseti brat'' (1866) je prvi roman slovenskega romanksepta. Jurčič je opisal Muljavo in dolenjsko podeželje ter jih s tem za vedno vpisal v slovensko literaturo.', 'muzej', 45.8617, 14.9089, NULL, 'dolenjska'),
  ('Kočevski Rog — pragozd', 'Največji in najstarejši pragozd v Evropi — brez človeškega posega 500+ let, dom divjih živali.', 'Kočevski Rog je eden redkih starih gozdov v Evropi brez cestne infrastrukture. Tu živijo medved, volk, ris, divja svinja — vsi Slovenijo divji sesalci v enem rezervatu.', 'gora', 45.6333, 14.9167, NULL, 'jugovzhodna_slovenija'),
  ('Kolpa — kopalinska reka', 'Najtoplejša reka v Sloveniji — kanuing, rafting, kopanje in ribolov ob slovensko-hrvaški meji.', 'Kolpa je najtoplejša reka v Alpsko-dinarskem prostoru — poleti 26–28 °C. V reki živijo postrvi, lipani in blistavka — vse tri vrste v čisti reki brez onesnaženja.', 'pot', 45.5389, 14.9667, NULL, 'jugovzhodna_slovenija'),
  ('Metlika — grad in vinska cesta', 'Belokranjski grad s trikratno cerkvijo — center belokranjske kulture, vina in plesnega izročila.', 'Metlika je znana po belih laških rizlingih in modri frankinjah. V gradu je edini muzej gasilства v Sloveniji. Belokranjska polka in trica se tu plešeta vsak vikend.', 'muzej', 45.6497, 15.3175, NULL, 'jugovzhodna_slovenija'),
  ('Park Lahinja', 'Naravni park v Beli krajini z izjemno biološko raznovrstnostjo — izviri, potoki in poplavni gozdovi.', 'V parku Lahinja živi orli belorepec — redka vrsta, ki je izginila iz večine Evrope. Park je del mednarodne Nature 2000 mreže in je zaščiten kot naravni rezervat.', 'pot', 45.5906, 15.3333, NULL, 'jugovzhodna_slovenija'),
  ('Izvir Kolpe', 'Skrivnostni izvir reke Kolpe v podgorski kraški jami — planinska pot skozi gozdove Gorjancev.', 'Kolpski izvir je še delno neraziskan — potapljači so segli do 100 m globine a niso dosegali konca. Voda pride iz podzemnih kanalov pod Gorjanci.', 'jezero', 45.5122, 14.7706, NULL, 'jugovzhodna_slovenija'),
  ('Ribnica — grad in rokodelstvo', 'Zgodovinsko ribniško mestece z gradom in 500-letno tradicijo suhe robe — sito, košara, lonci.', 'Robiška suha roba (leseno in pleteno posodje) je bila znana po vsej Avstriji — ribniški Kramars so prodajali po vsej Habsburški monarhiji. Tradicija je ohranje na UNESCO listi.', 'muzej', 45.7361, 14.7275, NULL, 'jugovzhodna_slovenija'),
  ('Kočevje — jezero in pragozd', 'Rekreacijsko jezero na mestu nekdanjega premogovnika in vhod v kočevske pragozde.', 'Pod jezerom so zaliti hodniki nekdanjega premogokopa — po nekaterih legenda je v globinah izgubljena rudarjeva oprema. Kočevski rog je 5 min vožnje — divje srce.', 'jezero', 45.6428, 14.8544, NULL, 'jugovzhodna_slovenija'),
  ('Dolenjski muzej Novo Mesto', 'Muzej z bogato halštatsko zbirko — bronasti situli, kelti ob Krki, 3000 let stare dragocene najdbe.', 'Novo Mesto je bilo v halštatski dobi eno najpomembnejših centrov v Alpah — situla iz Novega mesta je primer vrhunskega brončarskocraft-a. Bogastvo je izhajalo iz nadzora reke Krke.', 'muzej', 45.8011, 15.1697, NULL, 'jugovzhodna_slovenija')
ON CONFLICT DO NOTHING;

-- ── 3. Green Stamps — guests collect stamps for eco stays ────────────────────

CREATE TABLE IF NOT EXISTS public.green_badges (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ime         TEXT NOT NULL,
  opis        TEXT,
  ikona       TEXT,
  stopnja     INTEGER DEFAULT 1,
  ustvarjeno  TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.kmetija_green_badges (
  kmetija_id  UUID REFERENCES public.kmetije(id) ON DELETE CASCADE,
  badge_id    UUID REFERENCES public.green_badges(id) ON DELETE CASCADE,
  dodeljeno   TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (kmetija_id, badge_id)
);

CREATE TABLE IF NOT EXISTS public.green_stamps (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gost_id         UUID NOT NULL REFERENCES public.profili(id) ON DELETE CASCADE,
  kmetija_id      UUID NOT NULL REFERENCES public.kmetije(id) ON DELETE CASCADE,
  rezervacija_id  UUID REFERENCES public.rezervacije(id) ON DELETE SET NULL,
  ustvarjeno      TIMESTAMPTZ DEFAULT NOW(),
  skenirano       BOOLEAN DEFAULT TRUE
);

-- One stamp per guest per farm (unique index — reservation link prevents abuse)
CREATE UNIQUE INDEX IF NOT EXISTS green_stamps_unique
  ON public.green_stamps (gost_id, kmetija_id);

ALTER TABLE public.green_badges       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kmetija_green_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.green_stamps       ENABLE ROW LEVEL SECURITY;

-- Badges: public read
CREATE POLICY "green_badges_javno"         ON public.green_badges         FOR SELECT USING (true);
CREATE POLICY "kmetija_green_badges_javno" ON public.kmetija_green_badges FOR SELECT USING (true);

-- Stamps: each guest sees only their own
CREATE POLICY "green_stamps_gost"   ON public.green_stamps FOR SELECT USING (gost_id = auth.uid());
CREATE POLICY "green_stamps_insert" ON public.green_stamps FOR INSERT WITH CHECK (gost_id = auth.uid());

-- Admin full access
CREATE POLICY "green_badges_admin"    ON public.green_badges    FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profili WHERE id = auth.uid() AND vloga = 'super_admin')
);
CREATE POLICY "green_stamps_admin"    ON public.green_stamps    FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profili WHERE id = auth.uid() AND vloga = 'super_admin')
);

-- Service role can insert stamps on confirmed booking
GRANT INSERT ON public.green_stamps TO service_role;
